#!/usr/bin/env zsh

if [[ "$@" ]]; then
  lock=(xautolock -locknow)
  case "$@" in
  Lock) $lock ;;
  Logout) i3-msg exit ;;
  Reboot) reboot ;;
  "Power off") poweroff ;;
  Suspend)
    $lock
    systemctl suspend
    ;;
  Hibernate)
    $lock
    systemctl hibernate
    ;;
  "Hibernate and suspend")
    $lock
    systemctl hybrid-sleep
    ;;
  *) echo "what is that?" ;;
  esac
else
  OPTIONS="\
Lock
Logout
Reboot
Power off
Suspend
Hibernate
Hibernate and suspend"

  echo -e "$OPTIONS"
fi
