#!/usr/bin/env zsh

# If second param is unused then set theme normal, 
# else show theme list and use second param as offset for active line 
# (needed if additional line is inserted at top e.g. menu)
OFFSET=0
[[ "$2" ]] || THEME="$1" && OFFSET="$2"

if [[ "$THEME" ]]
then
  source $HOME/.config/wpg/scripted_themes/theme_func.sh
  
  case "$THEME" in
    goes)     goes &!;;
    lakeside) lakeside &!;;
    himawari) himawari &!;;
    random)   wpg -m &!;;
    reset)    wpg -s $(wpg -c) &!;;
    *)        wpg -s "$THEME" &!;;
  esac >/dev/null

else
  themes=$(wpg -l)
  scripted_themes="goes
himawari
lakeside"
  
  
  out="random\nreset\n$themes\n$scripted_themes"

  # highlight current theme
  current=$(wpg -c)
  
  case "$current" in
    goes*)     current="goes";;
    lakeside*) current="lakeside";;
    himawari*) current="himawari";;
  esac  >/dev/null

  current_line=$(echo "$out" | grep -an "$current" | cut -f1 -d:)

 
  echo -en "\0markup-rows\x1ftrue\n"
  echo -en "\0message\x1fCurrent theme: $current\n"
  echo -e "\0active\x1f$((current_line-1+OFFSET))"
  echo "$out"
  fi

